"""
ebook_fix.modules.paragraph

Uses the paragraph findings the analyzer already collected (see
ebook_fix.paragraphs) instead of re-scanning the book:

1. Empty paragraphs - leftover <p></p> tags with no real content, usually artifacts of a PDF or HTML conversion. One kind is not removed but kept as a scene break: a blank paragraph (one holding a non-breaking space or a line break) sitting between two paragraphs of story text, in a book where such gaps are rare. Many books mark a scene change that way, and deleting the blank paragraph silently joins the two scenes. These become a centered "* * *", the same marker Scene Break Normalizer uses. Several blank paragraphs in a row count as one break. A blank paragraph next to a heading, a rule, or an existing marker, in a chapter that is mostly padding, or in a book that has one between most paragraphs, is spacing and is removed as before (see the thresholds above).
2. Watermark / junk paragraphs - promotional lines left behind by whatever tool originally converted the file (e.g. "Generated by ABC Amber LIT Converter"), often dropped right in the middle of a sentence.
3. Mid-sentence paragraph splits - a paragraph that was cut off before it reached the end of a sentence, with the rest of the sentence sitting in a later paragraph, usually with empty and/or watermark paragraphs sitting in between. This is a classic symptom of eBooks generated from raw page-by-page PDF text.

Merging can chain (merge B into A, and the result now also looks
mid-sentence with C), so repair still walks the meaningful-paragraph
list live while it merges rather than just applying a frozen list of
pairs -- see ebook_fix.paragraphs for why that list is handed over
instead of the pairs themselves.

If this ever runs without an analysis handed to it, it falls back to
scanning the book itself via ebook_fix.paragraphs.analyze_book_paragraphs.
"""

from __future__ import annotations

import re

from ebook_fix.config import ParagraphRepairConfig
from ebook_fix.report import Report
from ebook_fix.paragraphs import analyze_book_paragraphs, looks_mid_sentence
from ebook_fix.modules.scene_break_repair import SCENE_BREAK_TEXT

# A blank paragraph standing between two stretches of story is only
# read as a scene break when blank paragraphs are rare in the book. A
# book that has one between most paragraphs is just padded for spacing.
MAX_BOOK_SPACER_RATIO = 0.15      # blank gaps per paragraph, whole book
MAX_CHAPTER_SPACER_RATIO = 0.30   # same, within one chapter
MIN_BOOK_PARAGRAPHS = 40          # too little text to judge a pattern
MIN_CHAPTER_PARAGRAPHS = 5        # title pages, copyright pages, etc.
HEADING_TAGS = {"h1", "h2", "h3", "h4", "h5", "h6"}
MARKER_TEXT = re.compile(r"^[\W_]{1,12}$")



def _local(el) -> str:
    tag = el.tag
    if not isinstance(tag, str):
        return ""
    return tag.split("}", 1)[1] if tag.startswith("{") else tag


def _text(el) -> str:
    return "".join(el.itertext()).strip()


def _is_blank_p(el) -> bool:
    return _local(el) == "p" and not _text(el) and not el.findall(".//{*}img")


def _renders_blank_line(el) -> bool:
    """True if an empty paragraph was written to show as a blank line:
    it holds a non-breaking space or a line break. A bare <p></p>, a
    paragraph of plain whitespace, or an empty classed paragraph is the
    kind of leftover a converter produces, and is not treated as a
    deliberate gap."""
    if el.findall(".//{*}br"):
        return True
    return any("\u00a0" in (t or "") for t in el.itertext())


def _sibling_elements(el, step):
    node = el.getprevious() if step < 0 else el.getnext()
    while node is not None:
        if isinstance(node.tag, str):
            return node
        node = node.getprevious() if step < 0 else node.getnext()
    return None


def _is_story_text(el, junk) -> bool:
    if el is None or el in junk or _local(el) not in ("p", "div"):
        return False
    text = _text(el)
    return bool(text) and not MARKER_TEXT.match(text)


def _spacer_runs(chapter_summary):
    """Runs of adjacent blank paragraphs sitting between two story
    paragraphs, as lists of live elements. Only runs that contain at
    least one paragraph that renders a gap are returned."""
    blanks = {ref.element for ref in chapter_summary.empty_paragraphs}
    junk = {ref.element for ref in chapter_summary.junk_elements}
    runs, seen = [], set()
    for el in blanks:
        if el in seen:
            continue
        # Walk to the start of the run, then collect it forward.
        start = el
        while True:
            before = _sibling_elements(start, -1)
            if before is not None and _is_blank_p(before):
                start = before
            else:
                break
        run, node = [], start
        while node is not None and _is_blank_p(node):
            run.append(node)
            node = _sibling_elements(node, +1)
        seen.update(run)
        if not any(r in blanks and _renders_blank_line(r) for r in run):
            continue
        if _is_story_text(_sibling_elements(run[0], -1), junk) and _is_story_text(node, junk):
            runs.append(run)
    return runs


def plan_spacers(paragraphs) -> dict:
    """Decides which blank paragraphs become scene breaks. Returns
    {element: run} for the first element of each run to convert; every
    other blank paragraph is removed as it always was."""
    per_chapter = []
    total_runs = total_paragraphs = 0
    for chapter_summary in paragraphs.chapters:
        runs = _spacer_runs(chapter_summary) if chapter_summary.empty_paragraphs else []
        count = len(chapter_summary.meaningful_paragraphs)
        per_chapter.append((runs, count))
        total_runs += len(runs)
        total_paragraphs += count

    if total_paragraphs < MIN_BOOK_PARAGRAPHS or total_runs / total_paragraphs > MAX_BOOK_SPACER_RATIO:
        return {}

    plan = {}
    for runs, count in per_chapter:
        if count < MIN_CHAPTER_PARAGRAPHS or len(runs) / count >= MAX_CHAPTER_SPACER_RATIO:
            continue
        for run in runs:
            plan[run[0]] = run
    return plan


def _make_scene_break(p) -> None:
    for child in list(p):
        p.remove(child)
    p.text = SCENE_BREAK_TEXT
    for attr in list(p.attrib):
        del p.attrib[attr]
    p.set("style", "text-align: center;")


class ParagraphRepair:
    name = "Paragraph Repair"

    def __init__(self, config: ParagraphRepairConfig | None = None):
        self.config = config or ParagraphRepairConfig()

    # -----------------------------------------------------
    # Analysis
    # -----------------------------------------------------

    def analyze(self, book, analysis=None):
        report = Report(self.name)
        paragraphs = analysis.paragraphs if analysis is not None else analyze_book_paragraphs(book)
        plan = plan_spacers(paragraphs) if self._convert_spacers() else {}

        for chapter_summary in paragraphs.chapters:
            if self.config.fix_watermark_junk:
                for _ in chapter_summary.junk_elements:
                    report.add(chapter_summary.href, "Conversion watermark / junk paragraph")

            if self.config.fix_empty_paragraphs:
                for ref in chapter_summary.empty_paragraphs:
                    if ref.element in plan:
                        report.add(chapter_summary.href, "Blank paragraph marking a scene break")
                    else:
                        report.add(chapter_summary.href, "Empty paragraph")

            if self.config.fix_mid_sentence_splits:
                for _ in chapter_summary.mid_sentence_splits:
                    report.add(chapter_summary.href, "Paragraph split mid-sentence")

        return report

    # -----------------------------------------------------
    # Repair
    # -----------------------------------------------------

    def repair(self, book, analysis=None):
        report = Report(self.name)
        paragraphs = analysis.paragraphs if analysis is not None else analyze_book_paragraphs(book)
        by_href = {c.href: c for c in paragraphs.chapters}
        plan = plan_spacers(paragraphs) if self._convert_spacers() else {}

        for chapter in book.chapters:
            chapter_summary = by_href.get(chapter.href)
            if chapter_summary is None:
                continue

            changed = False

            # Merge paragraph splits first. Walked live (not just the
            # precomputed pairs) since a merge can make the result look
            # mid-sentence with its new neighbor too.
            if self.config.fix_mid_sentence_splits:
                meaningful = list(chapter_summary.meaningful_paragraphs)
                i = len(meaningful) - 2

                while i >= 0:
                    first = meaningful[i]
                    second = meaningful[i + 1]

                    if looks_mid_sentence(first, second):
                        first_text = self._preview_text(first)
                        second_text = self._preview_text(second)
                        self._merge(first, second)
                        meaningful.pop(i + 1)
                        changed = True
                        report.add(
                            chapter.href,
                            "Paragraph split mid-sentence merged",
                            f"Merged paragraph ending {first_text!r} with the next "
                            f"one starting {second_text!r}.",
                        )

                    i -= 1

            # Remove empty paragraphs.
            if self.config.fix_empty_paragraphs:
                for ref in chapter_summary.empty_paragraphs:
                    p = ref.element
                    parent = p.getparent()

                    if p in plan and parent is not None:
                        _make_scene_break(p)
                        changed = True
                        report.add(
                            chapter.href,
                            "Blank paragraph converted to scene break",
                            "A blank paragraph between two paragraphs of story text "
                            f"now reads {SCENE_BREAK_TEXT!r}, so the scene change is not lost.",
                        )
                    elif parent is not None:
                        parent.remove(p)
                        changed = True
                        report.add(
                            chapter.href,
                            "Empty paragraph removed",
                            "Removed an empty <p></p> with no real content.",
                        )

            # Remove watermark junk.
            if self.config.fix_watermark_junk:
                for ref in chapter_summary.junk_elements:
                    el = ref.element
                    parent = el.getparent()

                    if parent is not None:
                        text = self._preview_text(el)
                        parent.remove(el)
                        changed = True
                        report.add(
                            chapter.href,
                            "Conversion watermark / junk paragraph removed",
                            f"Removed watermark/junk paragraph: {text!r}",
                        )

            if changed:
                chapter.modified = True
                book.mark_modified()

        return report

    # -----------------------------------------------------
    # Helpers
    # -----------------------------------------------------

    def _convert_spacers(self) -> bool:
        return self.config.fix_empty_paragraphs and getattr(
            self.config, "convert_spacers_to_scene_breaks", True
        )

    def _merge(self, first, second):
        """Append second paragraph onto first, then remove second."""

        if first.text is None:
            first.text = ""

        if len(first) == 0:
            first.text = (
                (first.text or "")
                + " "
                + (second.text or "").lstrip()
            )
        else:
            last_child = first[-1]
            last_child.tail = (
                (last_child.tail or "")
                + " "
                + (second.text or "").lstrip()
            )

        for child in list(second):
            first.append(child)

        parent = second.getparent()

        if parent is not None:
            parent.remove(second)

    def _preview_text(self, element, max_length: int = 60) -> str:
        """Short, single-line snippet of an element's text for use in
        repair-report descriptions -- full paragraphs would make the
        report unreadable, so this trims to a preview instead."""
        text = "".join(element.itertext()).strip()
        text = " ".join(text.split())
        if len(text) > max_length:
            text = text[:max_length].rstrip() + "..."
        return text