"""
ebook_fix.modules.paragraph

Uses the paragraph findings the analyzer already collected (see
ebook_fix.paragraphs) instead of re-scanning the book:

1. Empty paragraphs - leftover <p></p> tags with no real content, usually artifacts of a PDF or HTML conversion.
2. Watermark / junk paragraphs - promotional lines left behind by whatever tool originally converted the file (e.g. "Generated by ABC Amber LIT Converter"), often dropped right in the middle of a sentence.
3. Mid-sentence paragraph splits - a paragraph that was cut off before it reached the end of a sentence, with the rest of the sentence sitting in a later paragraph, usually with empty and/or watermark paragraphs sitting in between. This is a classic symptom of eBooks generated from raw page-by-page PDF text.

Merging can chain (merge B into A, and the result now also looks
mid-sentence with C), so repair still walks the meaningful-paragraph
list live while it merges rather than just applying a frozen list of
pairs -- see ebook_fix.paragraphs for why that list is handed over
instead of the pairs themselves.

If this ever runs without an analysis handed to it, it falls back to
scanning the book itself via ebook_fix.paragraphs.analyze_book_paragraphs.
"""

from __future__ import annotations

from ebook_fix.config import ParagraphRepairConfig
from ebook_fix.report import Report
from ebook_fix.paragraphs import analyze_book_paragraphs, looks_mid_sentence


class ParagraphRepair:
    name = "Paragraph Repair"

    def __init__(self, config: ParagraphRepairConfig | None = None):
        self.config = config or ParagraphRepairConfig()

    # -----------------------------------------------------
    # Analysis
    # -----------------------------------------------------

    def analyze(self, book, analysis=None):
        report = Report(self.name)
        paragraphs = analysis.paragraphs if analysis is not None else analyze_book_paragraphs(book)

        for chapter_summary in paragraphs.chapters:
            if self.config.fix_watermark_junk:
                for _ in chapter_summary.junk_elements:
                    report.add(chapter_summary.href, "Conversion watermark / junk paragraph")

            if self.config.fix_empty_paragraphs:
                for _ in chapter_summary.empty_paragraphs:
                    report.add(chapter_summary.href, "Empty paragraph")

            if self.config.fix_mid_sentence_splits:
                for _ in chapter_summary.mid_sentence_splits:
                    report.add(chapter_summary.href, "Paragraph split mid-sentence")

        return report

    # -----------------------------------------------------
    # Repair
    # -----------------------------------------------------

    def repair(self, book, analysis=None):
        paragraphs = analysis.paragraphs if analysis is not None else analyze_book_paragraphs(book)
        by_href = {c.href: c for c in paragraphs.chapters}

        for chapter in book.chapters:
            chapter_summary = by_href.get(chapter.href)
            if chapter_summary is None:
                continue

            changed = False

            # Merge paragraph splits first. Walked live (not just the
            # precomputed pairs) since a merge can make the result look
            # mid-sentence with its new neighbor too.
            if self.config.fix_mid_sentence_splits:
                meaningful = list(chapter_summary.meaningful_paragraphs)
                i = len(meaningful) - 2

                while i >= 0:
                    first = meaningful[i]
                    second = meaningful[i + 1]

                    if looks_mid_sentence(first, second):
                        self._merge(first, second)
                        meaningful.pop(i + 1)
                        changed = True

                    i -= 1

            # Remove empty paragraphs.
            if self.config.fix_empty_paragraphs:
                for ref in chapter_summary.empty_paragraphs:
                    p = ref.element
                    parent = p.getparent()

                    if parent is not None:
                        parent.remove(p)
                        changed = True

            # Remove watermark junk.
            if self.config.fix_watermark_junk:
                for ref in chapter_summary.junk_elements:
                    el = ref.element
                    parent = el.getparent()

                    if parent is not None:
                        parent.remove(el)
                        changed = True

            if changed:
                chapter.modified = True
                book.mark_modified()

    # -----------------------------------------------------
    # Helpers
    # -----------------------------------------------------

    def _merge(self, first, second):
        """Append second paragraph onto first, then remove second."""

        if first.text is None:
            first.text = ""

        if len(first) == 0:
            first.text = (
                (first.text or "")
                + " "
                + (second.text or "").lstrip()
            )
        else:
            last_child = first[-1]
            last_child.tail = (
                (last_child.tail or "")
                + " "
                + (second.text or "").lstrip()
            )

        for child in list(second):
            first.append(child)

        parent = second.getparent()

        if parent is not None:
            parent.remove(second)