"""
ebook_fix.modules.paragraph

Detects and repairs common issues in poorly-converted EPUBs:

1. Empty paragraphs - leftover <p></p> tags with no real content, usually artifacts of a PDF or HTML conversion.
2. Watermark / junk paragraphs - promotional lines left behind by whatever tool originally converted the file (e.g. "Generated by ABC Amber LIT Converter"), often dropped right in the middle of a sentence.
3. Mid-sentence paragraph splits - a paragraph that was cut off before it reached the end of a sentence, with the rest of the sentence sitting in a later paragraph, usually with empty and/or watermark paragraphs sitting in between. This is a classic symptom of eBooks generated from raw page-by-page PDF text.
"""

from __future__ import annotations
import re

from ebook_fix.config import ParagraphRepairConfig
from ebook_fix.report import Report

SENTENCE_ENDINGS = ('.', '!', '?', '"', "'", ')', '\u201d', '\u2019')

# Known conversion-tool watermark text.
JUNK_PATTERNS = (
    re.compile(r"generated by abc amber lit converter", re.IGNORECASE),
    re.compile(r"processtext\.com", re.IGNORECASE),
)

# Known conversion-tool watermark hyperlinks.
JUNK_URL_PATTERNS = (
    re.compile(r"https?://(?:www\.)?abbyy\.com(?:/|$)", re.IGNORECASE),
)


class ParagraphRepair:
    name = "Paragraph Repair"

    MIN_WORDS_FOR_MERGE = 4

    def __init__(self, config: ParagraphRepairConfig | None = None):
        self.config = config or ParagraphRepairConfig()

    # -----------------------------------------------------
    # Analysis
    # -----------------------------------------------------

    def analyze(self, book):
        report = Report(self.name)

        for chapter in book.chapters:

            if self.config.fix_watermark_junk:
                for el in self._junk_elements(chapter):
                    report.add(
                        chapter.href,
                        "Conversion watermark / junk paragraph",
                    )

            paragraphs = self._paragraphs(chapter)

            if self.config.fix_empty_paragraphs:
                for p in paragraphs:
                    if self._is_junk(p):
                        continue
                    if self._is_empty(p):
                        report.add(chapter.href, "Empty paragraph")

            if self.config.fix_mid_sentence_splits:
                meaningful = self._meaningful(paragraphs)

                for first, second in zip(meaningful, meaningful[1:]):
                    if self._looks_mid_sentence(first, second):
                        report.add(
                            chapter.href,
                            "Paragraph split mid-sentence",
                        )

        return report

    # -----------------------------------------------------
    # Repair
    # -----------------------------------------------------

    def repair(self, book):

        for chapter in book.chapters:

            changed = False
            meaningful = self._meaningful(self._paragraphs(chapter))

            # Merge paragraph splits first.
            if self.config.fix_mid_sentence_splits:

                i = len(meaningful) - 2

                while i >= 0:
                    first = meaningful[i]
                    second = meaningful[i + 1]

                    if self._looks_mid_sentence(first, second):
                        self._merge(first, second)
                        meaningful.pop(i + 1)
                        changed = True

                    i -= 1

            # Remove empty paragraphs.
            if self.config.fix_empty_paragraphs:

                for p in list(self._paragraphs(chapter)):
                    if self._is_empty(p):
                        parent = p.getparent()

                        if parent is not None:
                            parent.remove(p)
                            changed = True

            # Remove watermark junk.
            if self.config.fix_watermark_junk:

                for el in self._junk_elements(chapter):
                    parent = el.getparent()

                    if parent is not None:
                        parent.remove(el)
                        changed = True

            if changed:
                chapter.modified = True
                book.mark_modified()

    # -----------------------------------------------------
    # Helpers
    # -----------------------------------------------------

    def _paragraphs(self, chapter):
        if chapter.document is None:
            return []

        return chapter.document.findall(".//{*}p")

    def _meaningful(self, paragraphs):
        """Paragraphs that aren't empty and aren't watermark junk."""
        return [
            p
            for p in paragraphs
            if not self._is_empty(p) and not self._is_junk(p)
        ]

    def _text(self, element):
        return "".join(element.itertext()).strip()

    def _is_empty(self, element):
        if element.findall(".//{*}img"):
            return False

        return self._text(element) == ""

    def _junk_elements(self, chapter):
        """
        Return the outermost elements that represent conversion-tool
        watermarks.
        """

        if chapter.document is None:
            return []

        candidates = (
            chapter.document.findall(".//{*}div")
            + chapter.document.findall(".//{*}p")
            + chapter.document.findall(".//{*}a")
            + chapter.document.findall(".//{*}b")
        )

        matches = []
        matched_ids = set()

        for el in candidates:
            if self._is_junk(el):
                matches.append(el)
                matched_ids.add(id(el))

        # Keep only the outermost matching elements.
        return [
            el
            for el in matches
            if not any(
                id(parent) in matched_ids
                for parent in el.iterancestors()
            )
        ]

    def _is_junk(self, element):

        # Existing text-based watermark detection.
        text = self._text(element)

        if text:
            if any(pattern.search(text) for pattern in JUNK_PATTERNS):
                return True

        # Check hyperlinks inside the element.
        for a in element.findall(".//{*}a"):
            href = (a.get("href") or "").strip()

            if any(pattern.search(href) for pattern in JUNK_URL_PATTERNS):
                return True

        # If this element itself is an <a>, check it too.
        if element.tag.endswith("a"):
            href = (element.get("href") or "").strip()

            if any(pattern.search(href) for pattern in JUNK_URL_PATTERNS):
                return True

        return False

    def _looks_mid_sentence(self, first, second):

        first_text = self._text(first)
        second_text = self._text(second)

        if not first_text or not second_text:
            return False

        if len(first_text.split()) < self.MIN_WORDS_FOR_MERGE:
            return False

        if len(second_text.split()) < self.MIN_WORDS_FOR_MERGE:
            return False

        if first_text.endswith(SENTENCE_ENDINGS):
            return False

        return second_text[0].islower()

    def _merge(self, first, second):
        """Append second paragraph onto first, then remove second."""

        if first.text is None:
            first.text = ""

        if len(first) == 0:
            first.text = (
                (first.text or "")
                + " "
                + (second.text or "").lstrip()
            )
        else:
            last_child = first[-1]
            last_child.tail = (
                (last_child.tail or "")
                + " "
                + (second.text or "").lstrip()
            )

        for child in list(second):
            first.append(child)

        parent = second.getparent()

        if parent is not None:
            parent.remove(second)