"""
ebook_fix.paragraphs

Analyzes paragraph-level conversion artifacts during the same single
pass the rest of the analyzer runs, so ebook_fix.modules.paragraph
doesn't have to scan the book itself to find what needs fixing.

Three things get flagged, per chapter:

1. Empty paragraphs -- leftover <p></p> tags with no real content.
2. Watermark / junk paragraphs -- promotional text left behind by
   whatever tool originally converted the file.
3. Mid-sentence splits -- a paragraph cut off before the end of a
   sentence, continued (lowercase) in a later paragraph.

Detection here mirrors ebook_fix.modules.paragraph on purpose, since
the whole point is for that module to stop scanning itself and just
read these results. Each finding carries a live reference to the
actual element(s) involved so repair can act on them directly --
those references aren't saved to the JSON cache (see serialize.py),
only used within a single run.

One thing repair still has to do itself: merging can chain (merge B
into A, and the result now also looks mid-sentence with C), so this
module hands repair an ordered list of the meaningful paragraphs in
each chapter rather than a frozen list of merge pairs, and repair
still walks that list live while it merges. What this module saves
repair from redoing is the expensive part -- finding every paragraph
and checking each one for empty/junk -- not the merge walk itself.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field

SENTENCE_ENDINGS = ('.', '!', '?', '"', "'", ')', '\u201d', '\u2019')
MIN_WORDS_FOR_MERGE = 4

JUNK_PATTERNS = (
    re.compile(r"generated by abc amber lit converter", re.IGNORECASE),
    re.compile(r"processtext\.com", re.IGNORECASE),
    re.compile(r"^\s*page\s*[:.-]?\s*\d+\s*$", re.IGNORECASE),
)

JUNK_URL_PATTERNS = (
    re.compile(r"https?://(?:www\.)?abbyy\.com(?:/|$)", re.IGNORECASE),
)


@dataclass
class EmptyParagraph:
    href: str = ""
    element: object = None    # live <p> element; not saved to the JSON cache


@dataclass
class JunkElement:
    href: str = ""
    tag: str = ""
    preview: str = ""
    element: object = None    # live element; not saved to the JSON cache


@dataclass
class MidSentenceSplit:
    href: str = ""
    first_preview: str = ""
    second_preview: str = ""
    first: object = None      # live <p> element; not saved to the JSON cache
    second: object = None     # live <p> element; not saved to the JSON cache


@dataclass
class ChapterParagraphSummary:
    href: str = ""
    empty_paragraphs: list = field(default_factory=list)         # [EmptyParagraph]
    junk_elements: list = field(default_factory=list)            # [JunkElement]
    mid_sentence_splits: list = field(default_factory=list)      # [MidSentenceSplit]
    # Paragraphs that are neither empty nor junk, in document order --
    # this is what repair merges across. Not saved to the JSON cache
    # (see serialize.py), used within a single run only.
    meaningful_paragraphs: list = field(default_factory=list)


@dataclass
class BookParagraphSummary:
    chapters: list = field(default_factory=list)    # [ChapterParagraphSummary]

    @property
    def empty_paragraph_count(self) -> int:
        return sum(len(c.empty_paragraphs) for c in self.chapters)

    @property
    def junk_element_count(self) -> int:
        return sum(len(c.junk_elements) for c in self.chapters)

    @property
    def mid_sentence_split_count(self) -> int:
        return sum(len(c.mid_sentence_splits) for c in self.chapters)

    @property
    def chapters_with_issues(self) -> list:
        out = []
        for c in self.chapters:
            if c.empty_paragraphs or c.junk_elements or c.mid_sentence_splits:
                out.append(c.href)
        return out


def _text(element) -> str:
    return "".join(element.itertext()).strip()


def _is_empty(element) -> bool:
    if element.findall(".//{*}img"):
        return False
    return _text(element) == ""


def _is_junk(element) -> bool:
    text = _text(element)
    if text and any(pattern.search(text) for pattern in JUNK_PATTERNS):
        return True

    for a in element.findall(".//{*}a"):
        href = (a.get("href") or "").strip()
        if any(pattern.search(href) for pattern in JUNK_URL_PATTERNS):
            return True

    if isinstance(element.tag, str) and element.tag.endswith("a"):
        href = (element.get("href") or "").strip()
        if any(pattern.search(href) for pattern in JUNK_URL_PATTERNS):
            return True

    return False


def _junk_candidates(chapter):
    """Outermost elements that represent conversion-tool watermarks."""
    if chapter.document is None:
        return []

    candidates = (
        chapter.document.findall(".//{*}div")
        + chapter.document.findall(".//{*}p")
        + chapter.document.findall(".//{*}a")
        + chapter.document.findall(".//{*}b")
    )

    matches = []
    matched_ids = set()
    for el in candidates:
        if _is_junk(el):
            matches.append(el)
            matched_ids.add(id(el))

    return [
        el for el in matches
        if not any(id(parent) in matched_ids for parent in el.iterancestors())
    ]


def looks_mid_sentence(first, second) -> bool:
    first_text = _text(first)
    second_text = _text(second)

    if not first_text or not second_text:
        return False
    if len(first_text.split()) < MIN_WORDS_FOR_MERGE:
        return False
    if len(second_text.split()) < MIN_WORDS_FOR_MERGE:
        return False
    if first_text.endswith(SENTENCE_ENDINGS):
        return False

    return second_text[0].islower()


def _preview(text: str, limit: int = 60) -> str:
    text = text.strip()
    if len(text) <= limit:
        return text
    return text[:limit].rstrip() + "..."


def _tag_name(element) -> str:
    tag = element.tag
    if isinstance(tag, str) and tag.startswith("{"):
        return tag.split("}", 1)[1]
    return tag if isinstance(tag, str) else ""


def analyze_book_paragraphs(book) -> BookParagraphSummary:
    summary = BookParagraphSummary()

    for chapter in book.chapters:
        if chapter.document is None:
            continue

        chapter_summary = ChapterParagraphSummary(href=chapter.href)

        for el in _junk_candidates(chapter):
            chapter_summary.junk_elements.append(
                JunkElement(
                    href=chapter.href,
                    tag=_tag_name(el),
                    preview=_preview(_text(el)),
                    element=el,
                )
            )

        meaningful = []
        for p in chapter.document.findall(".//{*}p"):
            junk = _is_junk(p)
            empty = _is_empty(p)

            if not junk and empty:
                chapter_summary.empty_paragraphs.append(
                    EmptyParagraph(href=chapter.href, element=p)
                )
            if not junk and not empty:
                meaningful.append(p)

        chapter_summary.meaningful_paragraphs = meaningful

        for first, second in zip(meaningful, meaningful[1:]):
            if looks_mid_sentence(first, second):
                chapter_summary.mid_sentence_splits.append(
                    MidSentenceSplit(
                        href=chapter.href,
                        first_preview=_preview(_text(first)),
                        second_preview=_preview(_text(second)),
                        first=first,
                        second=second,
                    )
                )

        summary.chapters.append(chapter_summary)

    return summary
